# Generated by Django 5.0.14 on 2026-09-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamentu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naran",
                    models.CharField(max_length=100, verbose_name="Naran Departamentu"),
                ),
                (
                    "kodigu",
                    models.CharField(max_length=10, unique=True, verbose_name="Kódigu"),
                ),
                (
                    "deskrisaun",
                    models.TextField(blank=True, null=True, verbose_name="Deskrisaun"),
                ),
            ],
            options={
                "verbose_name_plural": "Departamentu Sira",
                "ordering": ["naran"],
            },
        ),
        migrations.CreateModel(
            name="SalaDeAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=50, verbose_name="Naran Sala")),
                ("kapasidade", models.IntegerField(verbose_name="Kapasidade")),
                (
                    "fatin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Fatin / Bloku",
                    ),
                ),
                ("deskrisaun", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Sala De Aula Sira",
                "ordering": ["naran"],
            },
        ),
        migrations.CreateModel(
            name="Dosente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naran",
                    models.CharField(max_length=150, verbose_name="Naran Kompletu"),
                ),
                (
                    "nid",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="NID (Númeru Identifikasaun Dosente)",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "telemovel",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Nu. Telemovel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Ativu", "Ativu"), ("La Ativu", "La Ativu")],
                        default="Ativu",
                        max_length=20,
                    ),
                ),
                (
                    "departamentu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosente_sira",
                        to="akademiku.departamentu",
                        verbose_name="Departamentu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dosente Sira",
                "ordering": ["naran"],
            },
        ),
    ]
