# Generated by Django 5.0.14 on 2026-09-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("akademiku", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nre",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="NRE (Númeru Rejistu Estudante)",
                    ),
                ),
                (
                    "naran_primeiru",
                    models.CharField(max_length=100, verbose_name="Naran Primeiru"),
                ),
                (
                    "naran_ikus",
                    models.CharField(max_length=100, verbose_name="Naran Ikus"),
                ),
                (
                    "jeneru",
                    models.CharField(
                        choices=[("M", "Mane"), ("F", "Feto")],
                        max_length=1,
                        verbose_name="Jéneru",
                    ),
                ),
                (
                    "fatin_moris",
                    models.CharField(max_length=100, verbose_name="Fatin Moris"),
                ),
                ("data_moris", models.DateField(verbose_name="Data Moris")),
                ("hela_fatin", models.TextField(verbose_name="Hela Fatin")),
                ("telefoni", models.CharField(max_length=15, verbose_name="Telefoni")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="foto_estudante/",
                        verbose_name="Foto",
                    ),
                ),
                ("tinan_tama", models.IntegerField(verbose_name="Tinan Tama")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ativu", "Ativu"),
                            ("La Ativu", "La Ativu"),
                            ("Graduadu", "Graduadu"),
                        ],
                        default="Ativu",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "departamentu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudante_sira",
                        to="akademiku.departamentu",
                        verbose_name="Departamentu",
                    ),
                ),
                (
                    "uza_nain",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konta Uza-Na'in",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Estudante Sira",
                "ordering": ["-tinan_tama", "naran_primeiru"],
            },
        ),
    ]
