# Generated by Django 5.0.14 on 2026-09-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("akademiku", "0001_initial"),
        ("estudante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kadeira",
                    models.CharField(max_length=150, verbose_name="Kadeira / Matéria"),
                ),
                ("data", models.DateField(verbose_name="Data Sesaun")),
                ("tempu_hahu", models.TimeField(verbose_name="Tempu Hahú")),
                ("tempu_remata", models.TimeField(verbose_name="Tempu Remata")),
                (
                    "deskrisaun",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deskrisaun / Tópiku"
                    ),
                ),
                (
                    "kodigu_qr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Kódigu QR (Token)",
                    ),
                ),
                (
                    "dosente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesaun_sira",
                        to="akademiku.dosente",
                        verbose_name="Dosente",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesaun_sira",
                        to="akademiku.saladeaula",
                        verbose_name="Sala de Aula",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sesaun Sira (Jadwal Kelas)",
                "ordering": ["-data", "-tempu_hahu"],
            },
        ),
        migrations.CreateModel(
            name="Presensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempu_tama",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tempu Tama (Scan)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Prezente", "Prezente"),
                            ("Falla", "Falla (Alfa)"),
                            ("Lisensa", "Lisensa (Ijin)"),
                            ("Moras", "Moras (Sakit)"),
                        ],
                        default="Prezente",
                        max_length=20,
                        verbose_name="Status Absensi",
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presensa_sira",
                        to="estudante.estudante",
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "sesaun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presensa_sira",
                        to="absensia.sesaun",
                        verbose_name="Sesaun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Presensa Sira (Data Absensi)",
                "ordering": ["-tempu_tama"],
                "unique_together": {("sesaun", "estudante")},
            },
        ),
    ]
